sonar.projectKey=aau-satellite-telemetry-system
sonar.projectName=Satellite Mission Control and Telemetry Management System
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
