spring:
  datasource:
    url: jdbc:h2:mem:satellite-it;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
server:
  port: 8080
  error:
    include-message: always
